### ISSUE TITLE
csv-meta-columns column ordinal

### ISSUE THREAD

**Issue by MarkPflug** [secretGeek/csvz#11]
With columns headers being optional in the 4180 spec, it might also be useful to specify/require the column ordinal in the meta-columns file. This would allow attaching headers to a csv via the column metadata.

For that matter, in the tables metadata would be useful to include a "HasHeaders" boolean column.

**Comment by secretGeek** [comment]
Absolutely true.

**Comment by secretGeek** [comment]
## Adding to `meta-columns`

- `ordinal` - the order in which the columns have been written to the file. In cases where there is no header row, or where columns are re-ordered, this can be helpful.

## Adding to `meta-tables`

  - `has-column-names` - a `true/false` value indicating if the file has a header row containing column names.
  - `skip-rows` - How many rows need to be skipped, before the data begins? (Rarely need to specify this, but when you need it, you need it!)

Keep the ideas coming @MarkPflug
