### ISSUE TITLE
how to specify delimiter types

### ISSUE THREAD

**Issue by secretGeek** [secretGeek/csvz#2]
could there be a way to specify the delimiters/qualifiers/ and other specifics/options

**Comment by secretGeek** [comment]
yes - idea is to put it into _meta/csv.csv

but how is that file to be read?????

🤔

It's a boot-strapping problem.

**Comment by doekman** [comment]
It could be solved to have more strict requirements for `_meta/csv.csv`.

It this file exists, it will strictly follow RFC 4180. This will also the first file has to be read, if it exists.

**Comment by secretGeek** [comment]
yeh i've mentioned it briefly now. 

ah, i'll add a spec fragment that says to comply with that strict rfc 4180 for the file csv.csv. That will be a separate fragment.

If they don't comply with it then they don't.

**Comment by doekman** [comment]
A good place to start is Python's CSV reader's [format parameters](https://docs.python.org/3.8/library/csv.html#csv-fmt-params).

**Comment by secretGeek** [comment]
closing this now as `_meta/csv.csv` is the definitely the answer. (Not that `_meta/csv.csv` is adequately documented.)

(Also, once `meta-per-file` (issue #10) is closed, you could write per-file descriptions of `{filename}.csv`  to `_meta/csv/{filename}.csv`
